### ISSUE TITLE
Missing informations in Firebase 

### ISSUE THREAD

**Issue by clement-petitcunot** [fastlane/fastlane-plugin-firebase_app_distribution#136]
Hi,

I worked with your pluggin today and it works very well. 
In order to optimize the deployment of our application, I removed "versionCode" & "versionName" from my "build.gradle" and I pass its information at compile time with the "gradle" command of Fastlane.

```
gradle(
        task: 'assemble',
        build_type: 'Debug',
        properties: {
            "versionCode" => ENV['VERSION_CODE'],
            "versionName" => ENV['VERSION_NAME']
         }
    )
```
My application compiles well but when it is deployed on Firebase App Distribution, the information is missing as you can see below.
- For the first, only one information miss because i put "versionCode" back
- The second one is correct because I put the information back to test.
- The last one is completely broken

![Capture d’écran 2020-08-28 à 17 32 16](https://user-images.githubusercontent.com/5476020/91585834-da775600-e954-11ea-8169-9f76d897582e.png)

Is there a way to work around this problem without having to put the information back into my "build.gradle"?

My "firebase_app_distribution" script : 
```
firebase_app_distribution(
      app: ENV['FIREBASE_ID'],
      apk_path: "app/build/outputs/apk/debug/app-debug.apk",
      testers: ENV['TESTERS']
    )
```

**Comment by rebehe** [comment]
Hi @clement-petitcunot, thanks for the detailed report! This is a feature we'll consider adding down the road, but the only way to get version info currently is by having it in your `build.gradle`.

**Comment by rebehe** [comment]
@clement-petitcunot I'm not sure exactly your use case, but you may be able to use https://github.com/beplus/fastlane-plugin-versioning_android to optimize your deployment instead

**Comment by clement-petitcunot** [comment]
Hi @rebehe, thanks for your answer.
Unfortunately the plugin you sent me doesn't answer my problem. It seems that we still need "versionCode" & "versionName" in the "build.gradle" ( or in the AndroidManifest ) for Firebase take it into account ( i tried to upload APK file without your plugin and still had the problem).
