### ISSUE TITLE
Changelog missing

### ISSUE THREAD

**Issue by danielgomezrico** [fastlane/fastlane-plugin-firebase_app_distribution#145]
Hi

I see a new release version 0.2.0 but I cant find what has changed and why should I update or not.

# Ideas
- Have a CHANGELOG.md file maybe with this format https://keepachangelog.com/en/1.0.0/ to explain that 
- Use github releases to document it

**Comment by cvaghela** [comment]
@danielgomezrico thanks for bringing this up. We are now looking into using Github releases and will probably start using it soon to document releases.

**Comment by lfkellogg** [comment]
Hi @danielgomezrico, we've decided to start using GitHub releases and created the first one for v0.2.0: https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v0.2.0

Thanks for the feedback!
