### ISSUE TITLE
Invalid APK file after upgrading to v0.2.0

### ISSUE THREAD

**Issue by tad3j** [fastlane/fastlane-plugin-firebase_app_distribution#146]
I've updated fastlane-plugin-firebase_app_distribution to v0.2.0 and I started getting error bellow when deploying to firebase:

```
App Distribution halted because it had a problem uploading the APK: There's been an error processing your distribution. Ensure you are uploading a valid IPA or APK and try again.
Additional information about this error:
Invalid APK file.
```
If I try to upload the APK file manually via their WEB service file gets uploaded without any issues. Also downgrading to v0.1.4 solves this issue and again lets fastlane upload apk file to fireabse app distribution server. 

Did I miss any breaking changes or could this be an issue with v0.2?

**Comment by cvaghela** [comment]
That is weird, if it works in the console and the previous plugin my guess is that we are somehow uploading the wrong file. Are you passing the `apk_path` or do you let the plugin find the file? Can you share your `Fastfile`?

**Comment by tad3j** [comment]
Yes, I am passing the `apk_path` and I haven't changed that since v0.1.4, so I think it should be pointing to the right file.

Maybe I should also mention that I use monorepo (in case this may be the issue?)...that's why I also pass `firebase_cli_path`, else plugin is looking for cli in wrong folder. Also, I'm running this on Windows.

Here are the relevant parts of my Fastfile:

```
default_platform(:android)

platform :android do
  desc "Yarn Install Dependencies"
  lane :yarn_install do |options|
    yarn(
      command: 'install',
      package_path: '../../..//package.json',
      options: '--ignore-optional --frozen-lockfile'
     )
  end

  desc "Build APK"
  lane :build_apk do |options|
    gradle(task: "clean")
    gradle(
      task: "assemble",
      build_type: options[:release] ? 'Release' : 'Releasestaging',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "project.keystore",
        "android.injected.signing.store.password" => options[:storePass],
        "android.injected.signing.key.alias" => "project",
        "android.injected.signing.key.password" => options[:keyPass],
      }
    )
  end

  desc "Distribute (Firebase App Distribution)"
  lane :staging do |options|
    yarn_install()
    build_apk(
      release: false,
      storePass: options[:storePass],
      keyPass: options[:keyPass]
    )
    firebase_app_distribution(
      app: options[:firebaseApp],
      groups: "group-1",
      firebase_cli_path: "../../../node_modules/.bin/firebase",
      apk_path: "./app/build/outputs/apk/releasestaging/app-releasestaging.apk"
    )
  end
end
```

**Comment by lfkellogg** [comment]
Sorry to prematurely close this issue. A fix has been merged but not released yet.

**Comment by lfkellogg** [comment]
@tad3j A new version was just released that should fix the issue. Can you please update your plugin to v0.2.1 and let us know if you're able to upload an APK?

Thanks,
Lee

**Comment by tad3j** [comment]
I can confirm that v0.2.1 fixes the issue on my side, great work.
