### ISSUE TITLE
Release version v0.2.3

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/fastlane-plugin-firebase_app_distribution#161]
Need to release - https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v0.2.3

@tagboola @lfkellogg Would either of you be able to release `v0.2.3` to Ruby gems? The fix is in (and tested) and version is bumped.

I don’t have access to `fastlane-plugin-firebase_app_distribution` but I’ve requested access from @snatchev (whenever he is able to give it to me). Not sure if either of you would be able to add me too (username is `joshdholtz`) but if you could that would be ❤

**Comment by lfkellogg** [comment]
Hi @joshdholtz I can release now and then we can try and get you access as well.

**Comment by joshdholtz** [comment]
@lfkellogg That would be great! I texted Stefan but I know he is off today so if you could build and push to Rubygems that would be 🔥

**Comment by lfkellogg** [comment]
Just pushed it up to Rubygems.

**Comment by joshdholtz** [comment]
Thank you! Really appreciate the quick response 🙌

**Comment by lfkellogg** [comment]
Just verified I'm able to fetch 0.2.3 from RubyGems and successfully post release notes. Thank you for turning this fix around so quickly!

**Comment by lfkellogg** [comment]
@joshdholtz Just FYI I went ahead and dropped a message in https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/159 and https://github.com/fastlane/fastlane/issues/17339, hope that's OK

**Comment by joshdholtz** [comment]
Of course! Thanks again ❤️
