### ISSUE TITLE
Not an "iOS App Store" profile

### ISSUE THREAD

**Issue by AAverin** [fastlane/fastlane-plugin-firebase_app_distribution#163]
Posting this here also https://github.com/fastlane/fastlane/issues/17349

According to Firebase Distribution, it should be possible to use Ad Hoc provisioning profile to publish.

Having Ad Hoc provisioning profile set up, fastlane fails to upload to Firebase App Distribution with error:

```
Error Domain=IDEProfileQualificationErrorDomain Code=3 "Provisioning profile "___" is not an "iOS App Store" profile." UserInfo={IDEProfileQualificationError_Profile=<IDEEmbeddedProvisioningProfile ___: name: ___, UUID: ___, teamName: ___, t
```

**Comment by lfkellogg** [comment]
@AAverin You're right, you should be able to upload ad-hoc builds to App Distribution.

Can you please share the output from running your fastlane command, as well as the lane definition in your Fastfile?

I suspect the build_ios_app (gym) action might be failing before the firebase_app_distribution action has a chance to run. Are you setting the export_method parameter to "ad-hoc"? (https://docs.fastlane.tools/actions/build_ios_app/#parameters)

**Comment by AAverin** [comment]
@lfkellogg I have shared some details here: https://github.com/fastlane/fastlane/issues/17349
Could you please take a look?

Here is my configuration:
```
  lane :alpha do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    firebase_app_distribution(
        app: "___",
        testers_file: "../distribution/testers.txt"
    )
  end
```
Do I need to do any extra setup for ad hoc?

**Comment by lfkellogg** [comment]
@AAverin Thanks for sharing that. Yes, unfortunately the docs aren't very clear on what the default is but I think you have to explicitly set export_method to "ad-hoc":

```
build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_method: "ad-hoc")
```

**Comment by AAverin** [comment]
Thanks, I will try today and see if it will work.

**Comment by AAverin** [comment]
It works with added export_method.
Thanks. Probably worth adding to the docs
