### ISSUE TITLE
Can't set CLI path using environment variable

### ISSUE THREAD

**Issue by jgongo** [fastlane/fastlane-plugin-firebase_app_distribution#170]
I'm trying to set the Firebase CLI path using the `FIREBASEAPPDISTRO_FIREBASE_CLI_PATH` environment variable. I use the `.env` support built into Fastlane, so I have an `.env.local` file which includes the following:

```
FIREBASEAPPDISTRO_FIREBASE_CLI_PATH=/usr/local/bin/firebase
```

Then, in my `Fastfile` I have the following:

```ruby
lane :deploy do
  flavor = ...
  artifact_name = ...
  firebase_app_distribution(
    # firebase_cli_path: ENV['FIREBASEAPPDISTRO_FIREBASE_CLI_PATH'], # Don't remove! Removing it causes fastlane to crash
    apk_path: "app/build/outputs/apk/#{flavor}/release/#{artifact_name}.apk",
    groups_file: "distribution/groups.#{flavor}.txt"
  )
end
```

and then I run this using

```sh
$ bundle exec fastlane --env local,dev deploy_to_firebase
``` 

(I have a different `FIREBASEAPPDISTRO_APP` defined depending on our target environment (dev, test, prod...))

If I comment the line with the `firebase_cli_path` parameter, I get the following error:

```
[13:53:19]: ---------------------------------------
[13:53:19]: --- Step: firebase_app_distribution ---
[13:53:19]: ---------------------------------------
[13:53:19]: Error setting value '/usr/local/bin/firebase' for option 'firebase_cli_path'
+---------------------+-------------------------------------+
|                       Lane Context                        |
+---------------------+-------------------------------------+
| ENVIRONMENT         | local,dev                           |
| DEFAULT_PLATFORM    | android                             |
| PLATFORM_NAME       | android                             |
| LANE_NAME           | android deploy                      |
+---------------------+-------------------------------------+
[13:53:19]: can't modify frozen String

```

My guess is that due to this line:

```ruby
      def self.run(params)
>>      params.values # to validate all inputs before looking for the ipa/apk
        cmd = [Shellwords.escape(params[:firebase_cli_path].chomp), FIREBASECMD_ACTION]
```

the parameters validation is being run twice (why?) and the second time the execution reaches the verify block the value is frozen in this line, where you try to chomp the string:

```ruby
verify_block: proc do |value|
>>value.chomp!
  if value.to_s == "" || !File.exist?(value)
    UI.user_error!("firebase_cli_path: missing path to firebase cli tool. Please install firebase in $PATH or specify path")
  end
```

and this error is raised. For whatever reason, putting the value as an explicit parameter doesn't cause the value to be frozen and the execution ends properly.

**Comment by lfkellogg** [comment]
Hi @jgongo, thanks for the report. Can you please update to the latest version of the plugin, v0.2.4?

The --firebase_cli_path param is deprecated as of v2.0.0, and the plugin is no longer dependent on the Firebase CLI (although it can optionally still use it for authentication). So if you update you should no longer hit this bug.

**Comment by jgongo** [comment]
Thanks, @lfkellogg! Updated to the latest version and now the problem is gone.
