### ISSUE TITLE
The adding testers and release notes steps stopped working recently some of the time

### ISSUE THREAD

**Issue by kroussevrb** [fastlane/fastlane-plugin-firebase_app_distribution#171]
We haven't changed anything in the way we use the fastlane task, and today two of the builds that were supposed to have testers and release notes added, ended up like this:

<img width="358" alt="Screen Shot 2020-10-20 at 16 42 40" src="https://user-images.githubusercontent.com/17250295/96594457-4e016800-12f3-11eb-8be5-6f95ba32b39a.png">

Several hours ago I was able to distribute a build normally:

<img width="325" alt="Screen Shot 2020-10-20 at 16 43 46" src="https://user-images.githubusercontent.com/17250295/96594564-6ec9bd80-12f3-11eb-9c30-b205cc67ab8d.png">

**Comment by jeremydurham** [comment]
Hi @kroussevrb - could you try again? We identified an issue that might have been causing this that should be fixed.

**Comment by kroussevrb** [comment]
> Hi @kroussevrb - could you try again? We identified an issue that might have been causing this that should be fixed.

Nope, same thing

A coworker found out that there was a new version of `firebase_app_distribution` and upgrading to it fixed the problem for him. However, I still think that the old version shouldn't've stopped working like that. 
<img width="314" alt="Screen Shot 2020-10-21 at 10 11 04" src="https://user-images.githubusercontent.com/17250295/96685446-c9135e80-1385-11eb-8d65-fcae5e95d13c.png">
