### ISSUE TITLE
googleservice_info_plist_path isn't relative to the Xcode project root but to the built product root

### ISSUE THREAD

**Issue by Valpertui** [fastlane/fastlane-plugin-firebase_app_distribution#172]
Hello,

I'm using fastlane `firebase_app_distribution`

In the documentation it is written :
> googleservice_info_plist_path | **The path to your GoogleService-Info.plist file, relative to the root of your Xcode project**. Set to GoogleService-Info.plist by default. The file is used to get your app's Firebase App ID if the app parameter is unspecified.

During testing, I noticed that in fact it was relative to the archived built product path (`/Users/XXXXX/Library/Developer/Xcode/Archives/XXXXXX/XXXXXX.xcarchive/Products/Applications/XXX.app/`)  

I believe that either the documentation should be updated, or the plist should properly be retrieved in the project hierarchy instead of the archive one.

Related to : https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/pull/46

**Comment by jeremydurham** [comment]
Thanks for pointing this out @Valpertui! We're working on pushing out a documentation update now.

**Comment by hilsenrat** [comment]
Hi @jeremydurham, I can open a new issue if you find that OK, but wouldn't it be more useful if the file path will be relative to the root project folder, and not to the product path?
