### ISSUE TITLE
Release notes for 2.0.0 point to moma..

### ISSUE THREAD

**Issue by compojoom** [fastlane/fastlane-plugin-firebase_app_distribution#177]
https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v0.2.0

The first 2 links in the description point to 
https://firebase.devsite.corp.google.com/docs/app-distribution/android/distribute-fastlane
https://firebase.devsite.corp.google.com/docs/app-distribution/ios/distribute-fastlane

which displays a site like this:
![grafik](https://user-images.githubusercontent.com/693770/99231063-63818900-27f0-11eb-8f1e-d5399e51bfd4.png)

**Comment by lfkellogg** [comment]
Hi @compojoom - thanks for the heads up. The links have been fixed.

Lee
