### ISSUE TITLE
Error with FIREBASE_TOKEN on multiple CI servers

### ISSUE THREAD

**Issue by tasvir-rohila-carsales** [fastlane/fastlane-plugin-firebase_app_distribution#186]
### Issue Description

The refresh token `FIREBASE_TOKEN` when generated from one CI machine works on it, but does not work on other two machines. 

Fastlane gives me `App Distribution could not generate credentials from the refresh token specified.` error for `firebase_app_distribution()` on "agents" running on other two CI machines

Steps followed: 
- $ firebase login:ci
- Visit this URL on this device to log in:
- Waiting for authentication...
- Success! Use this token to login on a CI server: 1//Oftxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-NE

How do I register the above token on the other two CI machines such that Firebase recognises it and I am able to distribute alpha builds to firebase.

##### Configuration

      firebase_app_distribution(
        ipa_path: ipa_path,
        app: firebase_app_id,
        release_notes: changelog,
        testers: tester_email,
        groups: tester_group,
        debug: true
      )

##### Complete verbose output

[16:19:58]: ---------------------------------------
  [16:19:58]: --- Step: firebase_app_distribution ---
  [16:19:58]: ---------------------------------------
16:19:58
  [16:19:58]: Authenticating with FIREBASE_TOKEN environment variable
  +------------------------------------+---------------+

  +------------------------------------+---------------+

  | DEFAULT_PLATFORM                   | ios            |

  | PLATFORM_NAME                      | ios            |

  | LANE_NAME                          | ios release    |

  | KEYCHAIN_PATH                      | XXX            |

  | SIGH_PROFILE_TYPE                  | ad-hoc         |

  | MATCH_PROVISIONING_PROFILE_MAPPING | XXX            |

  | IPA_OUTPUT_PATH                    | XXX            |

  | XCODEBUILD_ARCHIVE                 | XXX            |

  | DSYM_OUTPUT_PATH                   | XXX            |

  | FL_CHANGELOG                       | XXX            |

    +------------------------------------+---------------+

  []: App Distribution could not generate credentials from the refresh token specified.

##### Environment

| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.166.0 |
| fastlane-plugin-firebase_app_distribution | 0.2.5 |

**Comment by tagboola** [comment]
Hi @tasvir-rohila-carsales. This is actually working as intended. For your scenario, where you are doing server to server communication (or specifically CI machines to servers), I'd recommend using a service account.

https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane#service-acc-fastlane

**Comment by tasvir-rohila-carsales** [comment]
Hi @tagboola, thanks for your reply.
I would like to add that one common `$FIREBASE_TOKEN` used to work well on all our CI machines when it was included in a script that exports the `$FIREBASE_TOKEN` and executes the `Fastfile`. 

We wanted to secure the `$FIREBASE_TOKEN` and hence moved it from the said script to an environment variable in our CI server.

Why does the  `$FIREBASE_TOKEN` work well when exported from the script and not when passed as an environment variable in the CI ?

Thanks,
Tas

**Comment by tagboola** [comment]
@tasvir-rohila-carsales interesting. Can you share the example script that you used before where you exported the `$FIREBASE_TOKEN`, and the updates script where you pass it in as an environmental variable (making sure to leave out any sensitive information of course)?

**Comment by tasvir-rohila-carsales** [comment]
Hi @tagboola ,
My setup is working as expected now. That is `FIREBASE_TOKEN` is registered on the "main" machine running the CI application and the two CI machines then able to use that `FIREBASE_TOKEN` when connecting to Firebase for app distribution.

The reason why it stopped working was because of existing `FIREBASE_TOKEN` set in the bash profile on the two CI machines overriding the one coming from the "main" CI machine. 

Sorry for the confusion and thanks for your time though.

Cheers,
Tas

**Comment by tagboola** [comment]
Glad you were able to figure it out!
