### ISSUE TITLE
Silent failure on invalid release version name

### ISSUE THREAD

**Issue by ic** [fastlane/fastlane-plugin-firebase_app_distribution#209]
### Issue Description
We have an app for years now, always worked fine with Fastlane and the Firebase App Distribution plugin.

For the first time, we have released with a version named `0.2.7+rc1`, instead of the usual `0.2.7+2` (i.e. a number after the plus). It worked, but was ignored in the emails sent to tested, and actually overwrote (?) `0.2.7`. It seemed it ignored the build label. Later, we released `0.2.7+rc2`, which led to emails with `0.2.7 (2)`.

Later again, we released `0.2.7+gc`, so no number anymore. And here was the silent error:
* The lane execution works fine until the end. It warns of nothing unusual, and succeeds.
* Nothing happens after that. No warning in the CLI or the Firebase console. The new build does not appear in the list on the console.
* We then tried `0.2.7+3`, and that just worked as usual.

So the problem is in the build label being something else than a number.

Is this a  bug or a feature? Honestly I remember reading the build number must be a number... So it is definitely "my fault". However **the bug is the silent failure**. Choosing a non-number for the build number should raise an error and avoid magic. I believe a warning is not enough here.

Side note: It is pretty common to have RCs and GMs and betas, basically text labels to tag builds. An alternative to error management is to allow text, if Firebase allows it.

##### Configuration
```
firebase_app_distribution(
  app: 'app_id',
  testers: 'email@email.com',
  release_notes: 'release_notes',
)
```

##### Complete verbose output

[trace.txt](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/files/6627618/trace.txt)

##### Environment

| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.185.0 |
| fastlane-plugin-firebase_app_distribution | 0.2.9|

**Comment by tonybaroneee** [comment]
Hey Eric, thanks for the report. I wasn't able to reproduce locally. I set `0.2.7+rc1` as the `CFBundleShortVersionString` and `CFBundleVersion` to test both, and uploaded my test app via fastlane.

Here's what showed up in the dashboard: 
![image](https://user-images.githubusercontent.com/844249/121546791-9338ee00-c9d9-11eb-97e4-3a010e2152c4.png)

Where/how is your app version specified in your project?

**Comment by ic** [comment]
Thank you for looking into it. I came to realize an information is missing: I am using Flutter (2, not latest, but a few weeks old).

Would the problem be in Flutter or it’s integration with Fastlane?

**Comment by tonybaroneee** [comment]
Ah, gotcha. Probably the latter, perhaps it's having trouble parsing certain variations of non-conventional version strings. Unfortunately that's where my knowledge falls short 😅 .

**Comment by ic** [comment]
> Ah, gotcha. Probably the latter, perhaps it's having trouble parsing certain variations of non-conventional version strings. Unfortunately that's where my knowledge falls short 😅 .

Would you recommend where I could forward this? I will look at how the Flutter plug-ins are maintained in GitHut, but if someone knows the right place, appreciated!
