### ISSUE TITLE
Can't use googleservice_info_plist_path

### ISSUE THREAD

**Issue by rubenvereecken** [fastlane/fastlane-plugin-firebase_app_distribution#210]
### Issue Description
This continues on #172, as I haven't been able to get the `googleservice_info_plist_path` parameter to work.

I'm still not sure if I understand the clarification. I see that `googleservice_info_plist_path` is meant to be relative to the _archived product path_. 

So is that the `ipa_path`? Because for me, thats `./build/qa.ipa`. And the Google config file is at `./config/prod/GoogleService-Info.plist`. So I used
```
  lane :qa do
    firebase_app_distribution(
      googleservice_info_plist_path: "../config/prod/GoogleService-Info.plist",
      ipa_path: "build/lessgo-qa.ipa",
      groups: "qa-team"
    )
  end
```
But that didn't seem to do it, and neither did the simple version dropping the `../`.

##### Complete verbose output
```
[13:33:50]: ---------------------------------------                                                                                                                                                         
[13:33:50]: --- Step: firebase_app_distribution ---                                                                                                                                                         
[13:33:50]: ---------------------------------------                                                                                                                                                         +------------------+--------+                                                                                                                                                                               
|       Lane Context        |                                                                                                                                                                               +------------------+--------+                                                                                                                                                                               
| DEFAULT_PLATFORM | ios    |                                                                                                                                                                               
| PLATFORM_NAME    | ios    |                                                                                                                                                                               | LANE_NAME        | ios qa |                                                                                                                                                                               
+------------------+--------+                                                                                                                                                                               
[13:33:50]: Missing app id. Please check that the app parameter is set and try again 
```

**Comment by nathanielheitsch** [comment]
Having the same issue.

**Comment by tagboola** [comment]
Hi @rubenvereecken,

By `archived product path` we mean the path to your .app file when running `Product > Archive`. If you've added your `GoogleService-Info.plist` to your project and [added the config file to all targets](https://firebase.google.com/docs/ios/setup#add-config-file), the `GoogleService-Info.plist` should be included in your archived product path (along with other assets). Then you can set the`googleservice_info_plist_path` to the name of your config file (or if the name of the file is `GoogleService-Info.plist`  you can omit it since that's the [default value
](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane#step_3_set_up_your_fastfile_and_distribute_your_app))


Try updating your lane to this and see if it works.

```
lane :qa do
    firebase_app_distribution(
      googleservice_info_plist_path: "GoogleService-Info.plist",
      ipa_path: "build/lessgo-qa.ipa",
      groups: "qa-team"
    )
  end
```

**Comment by rebehe** [comment]
@rubenvereecken @nathanielheitsch following up - Given @tagboola's clarification, are you still running into this issue?

**Comment by rubenvereecken** [comment]
I understand

**Comment by sky1095** [comment]
> Hi @rubenvereecken,
> 
> By `archived product path` we mean the path to your .app file when running `Product > Archive`. If you've added your `GoogleService-Info.plist` to your project and [added the config file to all targets](https://firebase.google.com/docs/ios/setup#add-config-file), the `GoogleService-Info.plist` should be included in your archived product path (along with other assets). Then you can set the`googleservice_info_plist_path` to the name of your config file (or if the name of the file is `GoogleService-Info.plist` you can omit it since that's the [default value ](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane#step_3_set_up_your_fastfile_and_distribute_your_app))
> 
> Try updating your lane to this and see if it works.
> 
> ```
> lane :qa do
>     firebase_app_distribution(
>       googleservice_info_plist_path: "GoogleService-Info.plist",
>       ipa_path: "build/lessgo-qa.ipa",
>       groups: "qa-team"
>     )
>   end
> ```
Hey folks,
This doesn't work, still getting the same `Missing app id` error.
For some reason the app is still required even if the config file is added to the project.

```
platform :ios do
  desc "Push a new testing build to Firebase App Distribution"
  lane :distribute_to_firebase do |options|
    flavor = options[:flavor]
    build_path = "./build/firebase_app_distribution/#{flavor}/"

    # archive and export the ipa
    build_app(
      scheme: flavor,
      output_directory: build_path,
      export_method: "development",
    )
  
    # Upload the IPA file to Firebase App Distribution
    firebase_app_distribution(
      googleservice_info_plist_path: "GoogleService-Info.plist",
      ipa_path: "#{build_path}Runner.ipa",
      debug: true,
    )
  end
end

```

and the files under dir is like:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/16065933/221857375-3eadc942-6ef6-47f2-871e-ce3b6bbfe9c3.png">

**Comment by lfkellogg** [comment]
Hi @sky1095 - I think I'll need some more info to troubleshoot. Would you mind reaching out to me (`@Lee Kellogg`) on [Firebase community slack](https://firebase.community/)?

**Comment by vassily-fr** [comment]
Hi here, 

I still have this issue on april 2024. 
Any update ?

I my caes, the path to GoogleService-info.plist is ok since it work for my upload symbol lane.
but still no luck with firebase_app_distribution.

```
release = firebase_app_distribution(
                #app: "1:12345678:ios:123456476352aze2123", # preprod from google-info.plist <- works fine
                googleservice_info_plist_path: "./#{GEN_DIR}/../MyApp/Configuration/GoogleService-Info.plist", # not working :(
                testers: "truc@truc.com",
                release_notes: "#{RELEASE_NOTE_CONTENT}",
                ipa_path: "./#{GEN_DIR}/#{ipa_file_name}",
            )

upload_symbols_to_crashlytics(dsym_path: "./#{GEN_DIR}/#{dsym_file_name}",
                                            gsp_path: "./#{GEN_DIR}/../MyApp/Configuration/GoogleService-Info.plist",
                                            binary_path: "./#{GEN_DIR}/../Pods/FirebaseCrashlytics/upload-symbols")
```

looking foward to your update.
