### ISSUE TITLE
Support Ruby v 3.0.0p0

### ISSUE THREAD

**Issue by lupajz** [fastlane/fastlane-plugin-firebase_app_distribution#211]
### Issue Description
I've been updating our CI images and the latest one packs Ruby v3 by default, which causes crashes due to what I assume is an old dependency on google-api-client-0.38.0. I think a later version has support for this (https://github.com/googleapis/google-api-ruby-client/pull/900).

##### Complete verbose output
```
Resolving dependencies...
google-api-client-0.38.0 requires ruby version ~> 2.4, which is incompatible
with the current version, ruby 3.0.0p0
    
Exited with code exit status 5
```

| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.181.0 |
| fastlane-plugin-firebase_app_distribution | 0.2.7 |

**Comment by lfkellogg** [comment]
@lupajz Thanks for the report. Looks like we should probably update that dependency, however I'm not able to reproduce this with the latest versions of fastlane (2.187.0) and the plugin (0.2.9), when using Ruby 3.0.0p0. Could you try updating both and let me know if you're still experiencing the issue?

**Comment by lupajz** [comment]
@lfkellogg Thank you :+1: ! It seems to work after updating the Fastlane. Somehow the CI was running some older version of it.
