### ISSUE TITLE
App Distribution could not generate credentials from the service credentials file specified.

### ISSUE THREAD

**Issue by nyarian** [fastlane/fastlane-plugin-firebase_app_distribution#215]
### Issue Description

I have the plugin added to the configuration and `service_credentials_file`, `app`, `groups` and `release_notes` parameters specified for the action inside the lane. All the parameters are valid and the service account has `Firebase App Distribution Admin` role given. Nevertheless, the action fails with this error message: "[!] App Distribution could not generate credentials from the service credentials file specified. Service Account Path: /path/to/app/android/app/firebase_app_distribution_account_key.json". AppFile has a valid application id inside the `package_name` method. The same configuration applied to the Gradle's Firebase App Distribution Plugin works and the app was submitted successfully via plugin's task (appDistributionUploadRelease).

##### Configuration
Here's the complete lane's definition including the distribution action:

```ruby
  desc "Distributes the staging app via Firebase App Distribution"
  lane :distribute_firebase do
    build_android_app(
      task: "assemble",
      build_type: "Release"
    )

    firebase_app_distribution(
      service_credentials_file: "#{Dir.pwd.chomp("/fastlane")}/app/firebase_app_distribution_account_key.json",
      app: "app-id-copied-from-the-firebase-app-page",
      groups: "staging",
      release_notes: "Stub"
    )
  end
```

##### Complete verbose output

> user:~/path/to/app/android$ bundle exec fastlane android distribute_firebase
> [✔] 🚀 
> +-------------------------------------------+---------+-------------------------------------+
> |                                       Used plugins                                        |
> +-------------------------------------------+---------+-------------------------------------+
> | Plugin                                    | Version | Action                              |
> +-------------------------------------------+---------+-------------------------------------+
> | fastlane-plugin-firebase_app_distribution | 0.2.9   | firebase_app_distribution,          |
> |                                           |         | firebase_app_distribution_login,    |
> |                                           |         | firebase_app_distribution_get_udids |
> +-------------------------------------------+---------+-------------------------------------+
> 
> [03:11:02]: ------------------------------
> [03:11:02]: --- Step: default_platform ---
> [03:11:02]: ------------------------------
> [03:11:02]: Driving the lane 'android distribute_firebase' 🚀
> [03:11:02]: -----------------------------
> [03:11:02]: --- Step: assembleRelease ---
> [03:11:02]: -----------------------------
> [03:11:02]: $ /path/to/app/android/gradlew assembleRelease -p .
> [03:11:03]: ▸ > ...
> [03:11:05]: ▸ > Task :app:assembleRelease
> [03:11:05]: ▸ BUILD SUCCESSFUL in 3s
> [03:11:05]: ▸ 33 actionable tasks: 2 executed, 31 up-to-date
> [03:11:06]: ---------------------------------------
> [03:11:06]: --- Step: firebase_app_distribution ---
> [03:11:06]: ---------------------------------------
> [03:11:06]: Authenticating with --service_credentials_file path parameter: /path/to/app/android/app/firebase_app_distribution_account_key.json
> +-------------------------------------+----------------------------------------------------------------------------------+
> |                                                      Lane Context                                                      |
> +-------------------------------------+----------------------------------------------------------------------------------+
> | DEFAULT_PLATFORM                    | android                                                                          |
> | PLATFORM_NAME                       | android                                                                          |
> | LANE_NAME                           | android distribute_firebase                                                      |
> | GRADLE_BUILD_TYPE                   | Release                                                                          |
> | GRADLE_ALL_APK_OUTPUT_PATHS         | ["/path/to/app/android/app/build/outputs/apk/release/app-release.apk"]          |
> | GRADLE_ALL_AAB_OUTPUT_PATHS         | []                                                                               |
> | GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | []                                                                               |
> | GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS | ["/path/to/app/android/app/build/outputs/mapping/release/mapping.txt"] |
> | GRADLE_APK_OUTPUT_PATH              | /path/to/app/android/app/build/outputs/apk/release/app-release.apk |
> | GRADLE_MAPPING_TXT_OUTPUT_PATH      | /path/to/app/android/app/build/outputs/mapping/release/mapping.txt |
> +-------------------------------------+----------------------------------------------------------------------------------+
> [03:11:11]: App Distribution could not generate credentials from the service credentials file specified. Service Account Path: /path/to/app/android/app/firebase_app_distribution_account_key.json
> 
> +------+---------------------------+-------------+
> |                fastlane summary                |
> +------+---------------------------+-------------+
> | Step | Action                    | Time (in s) |
> +------+---------------------------+-------------+
> | 1    | default_platform          | 0           |
> | 2    | assembleRelease           | 3           |
> | 💥   | firebase_app_distribution | 4           |
> +------+---------------------------+-------------+
> 
> [03:11:11]: fastlane finished with errors
> 
> [!] App Distribution could not generate credentials from the service credentials file specified. Service Account Path: /path/to/app/android/app/firebase_app_distribution_account_key.json

##### Environment
| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.187.0 |
| fastlane-plugin-firebase_app_distribution | 0.2.9 |
| ruby | ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux] |
| bundler | 2.2.22 |

##### Worth noting

This error description seem to appear only in case if Google API respond with [authorization error](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/master/lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_auth_client.rb#L87). My guess was that the Fastlane plugin requests scopes which require additional roles to be granted, but giving Viewer and Editor roles to the service account changed nothing. I also tried to play around with service account key file access and even changing file owner - no luck here, too. Currently I don't have the slightest idea why it is not working, and Google's API request error message absence is of no help either, unfortunately.

As I mentioned, Gradle plugin with the same configuration works. Just in case, posting Gradle plugin's configuration here, too:

```groovy
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            firebaseAppDistribution {
                appId = "app-id-copied-from-the-firebase-app-page"
                serviceCredentialsFile = "$projectDir/firebase_app_distribution_account_key.json"
                groups = "staging"
                releaseNotes = "Stub"
            }
        }
    }
```

Here is the output:

> user:/path/to/app/android$ ./gradlew assembleRelease appDistributionUploadRelease
> 
> > Task :app:appDistributionUploadRelease
> Using APK path in the outputs directory: /path/to/app/android/app/build/outputs/apk/release/app-release.apk.
> Uploading APK to Firebase App Distribution...
> Getting appId from build.gradle file
> Using service credentials file specified by the serviceCredentialsFile property in your app's build.gradle file: /path/to/app/android/app/firebase_app_distribution_account_key.json
> This APK has not been uploaded before.
> Uploading the APK.
> Uploaded APK successfully 202
> Added release notes successfully 200
> Added testers/groups successfully 200
> App Distribution upload finished successfully!
> 
> BUILD SUCCESSFUL in 47s
> 34 actionable tasks: 14 executed, 20 up-to-date

**Comment by lfkellogg** [comment]
Hi @nyarian - thanks so much for the detailed report. It's definitely surprising that it's working in gradle but not fastlane. I'm not sure what the problem is at this point, and I think some more info would help.

I've put up a PR to print out more information about these types of errors: https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/pull/217

In the meantime, if you'd like to try this out locally you can check out the branch:
```
$ cd <dev root>
$ git clone git@github.com:fastlane/fastlane-plugin-firebase_app_distribution.git
$ cd fastlane-plugin-firebase_app_distribution
$ git checkout lk/auth-error-logging
```

Then use the local version of the plugin, by opening your app's `fastlane/Pluginfile` and adding the local path to the plugin's entry:
```
gem 'fastlane-plugin-firebase_app_distribution', path: '<dev root>/fastlane-plugin-firebase_app_distribution'
```

If you do try it out, let me know what it shows.

Thanks,
Lee

**Comment by nyarian** [comment]
Hello @lfkellogg

I was just in the middle of adding Play Store distribution routine via Fastlane when I received notification about your response via email. Thing is: Google Play connection based on the service account private key failed, which pointed out that there is some network-related issue with my environment, not with the plugin. `--verbose` flag got the error printed in when ran along `validate_play_store_json_key` lane, which ultimately drove me to solution. Thus, the error reporting PR certainly will be of much help for the users facing similar issue in future (I'd be glad to contribute it in the first place as well, but, alas, my Ruby proficiency can be described as "pathetic").

Just to make it "complete", I'll quickly describe my issue and the solution:

> Unexpected error: #<Faraday::SSLError wrapped=#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)>>

In the end it turned out that this [thing fixed](https://github.com/rubygems/rubygems/issues/2415#issuecomment-509806259) both Google Play and Firebase distribution via this plugin.

Sorry about making the issue here to ultimately conclude that it has nothing to do with the plugin: I didn't expect for issue to crawl here, clearly.

Thank you for your work and help, much appreciated!

**Comment by nyarian** [comment]
It seems that I can't remove the `bug` label for some reason, though...
