### ISSUE TITLE
Failed to add release notes: Release notes length exceeds maximum character limit

### ISSUE THREAD

**Issue by Aure77** [fastlane/fastlane-plugin-firebase_app_distribution#249]
### Issue Description
If the generated release note is too big, firebase_app_distribution failed with error: `Failed to add release notes: Release notes length exceeds maximum character limit`

What is the maximum length authorized ? It will be great to have an option to do not fail task if length exceeds or add a capability to truncate release notes.

##### Configuration
Use release notes file option `release_notes_file: "./android/RELEASE_NOTE.md",`

##### Complete verbose output

> [16:38:47]: fastlane finished with errors
> 
> [!] Failed to add release notes: Release notes length exceeds maximum character limit

| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.146.1 |
| fastlane-plugin-firebase_app_distribution | 0.2.5 |

**Comment by zakkhoyt** [comment]
I encountered this error today, however i used the `release_notes` parameter, not `release_notes_file`. 
Has either parameter been updated to accept larger payloads?

**Comment by rachaprince** [comment]
Hi @zakkhoyt,

Unfortunately the limit for both parameters is still 65536 bytes. App Distribution would be interesting in learning more about your use case, so if you have time to fill out a [feature request](https://firebase.google.com/support/troubleshooter/report/features) that would be very helpful!

**Comment by pankaj-badgujar** [comment]
Hi @rachaprince  Was this issue resolved?

**Comment by rebehe** [comment]
Hey, engineer on App Distribution here. The release limit is still 65536 bytes. We'd be curious to understand your use case better though. Why do you need a higher release limit?

**Comment by pankaj-badgujar** [comment]
Hi @rebehe, its not a blocker or a regular issue. Its an exception scenario for us where sometimes we have a feature branch to which we merge multiple commits, in such cases because the `beta_app_description` or `release_notes` parameter in the fastfile for our ios and android platforms  is set to `changelog_from_git_commits`, with an increasing changelog, they exceed 65536 bytes. This leads to our job failing that step in our pipeline.

I could not find a way to add a condition in the fastfile to trim those messages when they are exceeding the limit.
As I said, not a major blocker but would be nice to have it working.

**Comment by rebehe** [comment]
@pankaj-badgujar thanks for the context. Will relay this to the team.

**Comment by miketraverso** [comment]
Any update on this? Just ran into it. Same situation. Using `changelog_from_git_commits` from a my Fastlane `Fastfile`. Aren't Fastlane and Firebase both Google products? Shouldn't the two be compatible?

**Comment by pranjali420** [comment]
Is this resolve yet? I am facing same issue. Please suggest us the solution for it.

**Comment by cbillante-gpsw** [comment]
Run into this as well.  For our production (RCs) there could be quite a few bug fix references along with features. Be great if it does not fail.  Any progress on the truncation feature request?
