### ISSUE TITLE
iOS Distribution: Couldn't find binary.

### ISSUE THREAD

**Issue by sgrumo** [fastlane/fastlane-plugin-firebase_app_distribution#258]
### Issue Description
I've setup a Flutter project with latest version both fastlane ( 2.199.0 ) and fastlane-plugin-firebase_app_distribution ( 0.3.2 ). 
I've followed the documentation in order to distribute iOS application on Firebase ( which has been thoroughly setup up ). 

On the Fastfile I've implemented two different lanes, one for the build and one for the distribution: 

```firebase_app_id = "***-***"
ipa_build_path = "/Users/****/***/***/ios/build/Runner.ipa"
firebase_path = "/usr/local/bin/firebase"

app_testers = [
  "test@gmail.com",
  "test2@gmail.com"
]

lane :build do
  get_certificates()
  get_provisioning_profile(adhoc: true)
  increment_build_number(xcodeproj: "Runner.xcodeproj")
  build_app(workspace: "Runner.xcworkspace", export_method: "ad-hoc", silent: "true", build_path: "./build/", output_directory: "./build/")
end

lane :distribute do
  build
  firebase_app_distribution(
      app: firebase_app_id,
      release_notes: "Try out this app!",
      ipa_path: ipa_build_path,
      testers: app_testers.join(","),
      verbose: true
  )
end
```

The problem is that when I use the command `bundle exec fastlane distribute`
It always generates this error: 

```
fastlane finished with errors
[!] Couldn't find binary
```

I've checked che plugin source code and I've found that the error is generated from these lines of code:

https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/master/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb: 
```      
  binary_path = get_binary_path(platform, params)
  UI.user_error!("Couldn't find binary") if binary_path.nil?
```

I've looked in the source code of the `get_binary_path` function: ( https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/4fcb185f1a30f61a0e2c2413f0be2cd3b2d96d29/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L112 )
```
        if platform == :ios
          return params[:ipa_path] ||
                 Actions.lane_context[SharedValues::IPA_OUTPUT_PATH] ||
                 Dir["*.ipa"].sort_by { |x| File.mtime(x) }.last
        end
```
I hope I've provided all of the necessary informations. 

| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.199.0 |
| fastlane-plugin-firebase_app_distribution | 0.3.2 |

Machine I'm working on:
Mac mini 2018, MacOs Big Sur 11.3.1

**Comment by sgrumo** [comment]
Mmmh I think I've found a solution. In my Fastfile I haven't specified the platform.
I had only `default_platform(:ios)`. I thought that the platform would be automatically set to **ios** since it's default, but it's not. 
I had to wrap my lanes with `platform :ios do` in order to make it work. 
Is this a bug?

**Comment by tagboola** [comment]
Interesting. We get the platform by checking the value of `Actions::SharedValues::PLATFORM_NAME`.

https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/4fcb185f1a30f61a0e2c2413f0be2cd3b2d96d29/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L100-L102

Which is also what the `Fastlane::Helper::LaneHelper.current_platform` method  checks.

https://github.com/fastlane/fastlane/blob/e874a47c6e2e0e61590a03d3b71e75e5a505d1ce/fastlane/lib/fastlane/helper/lane_helper.rb#L4-L6
```
def self.current_platform
  return Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::PLATFORM_NAME]
end
```

But it looks like the `default_platform` method only updates `SharedValues::DEFAULT_PLATFORM` 
https://docs.fastlane.tools/actions/default_platform/

**Comment by lfkellogg** [comment]
Good find about the default platform. The plugin is supposed to fall back to the platform from the app ID though if there's no platform set: https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/4fcb185f1a30f61a0e2c2413f0be2cd3b2d96d29/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L23

@sgrumo is it possible the variable holding your app ID was not set at the time?
