### ISSUE TITLE
iOS: Could not enable access for testers

### ISSUE THREAD

**Issue by aytunch** [fastlane/fastlane-plugin-firebase_app_distribution#259]
My fastlane dist gets an error on the last step: firebase app distribution

> Could not enable access for testers. Check that the groups exist and the tester emails are formatted correctly 
> Emails:  
> Groups: ["iOS"]
> 

I tried my group name with lower case and capital letter but no luck (ios, iOS, IOS)
I am using the latest fastlane and firebase app dist plugin

<img width="982" alt="Screen Shot 2022-01-22 at 21 28 45" src="https://user-images.githubusercontent.com/6442915/150651045-9de87334-0235-4518-93bc-4181bc43390a.png">

<img width="622" alt="Screen Shot 2022-01-22 at 21 38 00" src="https://user-images.githubusercontent.com/6442915/150651322-5492363c-7907-4277-ae4f-3fa566e542d7.png">

**Comment by firebase-app-distro** [comment]
Hello! The group alias is case sensitive, so “ios” is the correct value to use based on the screenshot of the Firebase Console that you sent. Can you double check that you’re pointing to the correct project that contains that group?

**Comment by tonybaroneee** [comment]
Hello! The group alias is case sensitive, so “ios” is the correct value to use based on the screenshot of the Firebase Console that you sent. Can you double check that you’re pointing to the correct project that contains that group?
