### ISSUE TITLE
Existing Access Token

### ISSUE THREAD

**Issue by enchorb** [fastlane/fastlane-plugin-firebase_app_distribution#261]
### Issue Description
Hi, not sure if this files under a feature request instead, feel free to move it if so. 

Is there a way to authenticate if you already have an access token? Looking through the code of this plugin we provide the token from login:ci to retrieve an access token. 

In our CI/CD system we already have an access token (obtained from gcloud auth print-access-token), however when we pass this to the plugin (either through the env variable FIREBASE_TOKEN or the firebase_cli_token param) it generates a 401 unauthorized client error as I believe it using the access token as a refresh token to obtain another access token. 

##### Complete verbose output
```
Error fetching access token:
Authorization failed. Server message:
{
 "error": "unauthorized_client",
 "error_description": "Unauthorized"
}
```

##### Environment

Latest versions of both

**Comment by enchorb** [comment]
If this feature is not supported maybe it can be by adding an access_token param and doing something like this?: 

```
auth_token = params[:access_token] || fetch_auth_token(
          params[:service_credentials_file], params[:firebase_cli_token], params[:debug]
        )
```

**Comment by rebehe** [comment]
Hi @enchorb, thanks for reaching out! You're right, we currently don't support access tokens for authentication. Thanks for the feedback though, I'll pass it along to the team!
