### ISSUE TITLE
the server responded with status 404\e[0m (Faraday::ResourceNotFound)

### ISSUE THREAD

**Issue by Pavel1501** [fastlane/fastlane-plugin-firebase_app_distribution#273]
### Issue Description
I work as a DevOps engineer and I want to distribute my app to firebase.
My Fastfile:
```
lane :distribute do
    # Build
    build_ios_app(
      ...
    )
    
    # Upload to Firebase
    firebase_app_distribution(
      app: "***", 
      firebase_cli_token: "***",
      testers: "***", 
      release_notes: "***"
    )
  end
end
```
I use "fastlane distribute"  command to run the lane and after that I am getting 404 error (you can see output on screenshot)

![Screenshot from 2022-05-04 13-36-31](https://user-images.githubusercontent.com/61389311/166666046-b898a308-1ff5-41d4-8a73-608b4f03ebf1.png)

In the very end after that image I got logs that are followed by:
```
/Users/project/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.5.1/lib/faraday/response/raise_error.rb:22:in `on_complete': \e[31m[!] the server responded with status 404\e[0m (Faraday::ResourceNotFound)

```

| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.205.2 |
| fastlane-plugin-firebase_app_distribution | 0.3.4 |

**Comment by jladieu** [comment]
Thanks for reaching out!  Can you let me know if you're just starting to use the fastlane plugin for app distribution?  If so, there are some basic things we can try.

1) Verify if the Project ID or App ID used in your fastfile are correct.

2) If this is your first time working with it, it's possible you need to onboard your app.
- Go to your Firebase console
- Click App Distribution section under the Release & Monitor tab
- Select your project
- Verify if the “Get Started” button has been pressed

3) Add `debug` to your fastfile, rerun, and share the logs with us.  Some additional details might help narrow down the problem.

**Comment by Pavel1501** [comment]
Yeah, You are right, that`s the first time I work with Firebase. I did not press  Get Started button. Thank you for advice!!!

**Comment by jladieu** [comment]
Awesome!  Glad this helped.  Enjoy app distribution!  We'd love to know what you think as you get started.

**Comment by cvb941** [comment]
I spent some time today on this until I found this GitHub Issue. Would be great to have an error description in the output log somehow to direct people to press the Get Started button first in the Firebase console.
