### ISSUE TITLE
App Distribution could not generate credentials from the refresh token specified

### ISSUE THREAD

**Issue by naiemmlbd** [fastlane/fastlane-plugin-firebase_app_distribution#276]
### Issue Description
Can't distribute app using Firebase app distribution. I have tried to distribute the app with the same token from another machine, and it worked. But it's not working on my MacBook. I have tried almost all the solutions from the web.

##### Complete verbose output

[!] App Distribution could not generate credentials from the refresh token specified.
Refresh token used: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
" (redacted)
Authorization failed.  Server message:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
Response status: 400

##### Environment
Using all the latest version.

| Library     | Version |
| ----------- | ----------- |
| fastlane | [2.208.0] |
| fastlane-plugin-firebase_app_distribution | [0.3.4] |

**Comment by lfkellogg** [comment]
@naiemmlbd In your verbose output it appears there is a newline at the end of your refresh token:

> Refresh token used: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXgyRs
> " <-- closing quote is on a new line

I tried this locally and this does result in the error you saw.

How are you setting your refresh token? Is it possible the newline was added when copying/pasting?

**Comment by naiemmlbd** [comment]
> @naiemmlbd In your verbose output it appears there is a newline at the end of your refresh token:
> 
> > Refresh token used: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXgyRs
> > " <-- closing quote is on a new line
> 
> I tried this locally and this does result in the error you saw.
> 
> How are you setting your refresh token? Is it possible the newline was added when copying/pasting?

"Saving file with a line break" - option was enabled in my IDE. 
Thank you so much.
