### ISSUE TITLE
Get link to release

### ISSUE THREAD

**Issue by AndrewSB** [fastlane/fastlane-plugin-firebase_app_distribution#285]
Hey! after the step runs, is there some way to get a link to the new release on the firebase console? i want to share the link to an internal messenger after the release succeeds

**Comment by AndrewSB** [comment]
i suppose i could use `firebase_app_distribution_get_latest_release`, but i'm worried about race conditions where there might be two simultaneous uploads

**Comment by Yerdikul** [comment]
+1

**Comment by jinthagerman** [comment]
+1

**Comment by abdullahumer** [comment]
Need the same.

**Comment by norealityagent** [comment]
Hey folks, we are working on sharing links to the binary and other release info in the plugin right now, expect an update soon!

**Comment by angelica-snowit** [comment]
I see the links printed out in console, but I'm trying to implement a post to slack with the link. Any chance to have them in a variable?

**Comment by rebehe** [comment]
@angelica-snowit, thanks for the feedback! Your use case makes a lot of sense. I'll pass this feedback along to our PM and the team. However, we would also encourage you to consider [contributing directly](https://opensource.google/documentation/reference/releasing/template/CONTRIBUTING) and send us a PR.

**Comment by cameronstanley** [comment]
@angelica-snowit We saw the same thing when messing with our own use case. Thought I would mention it looks like you can use the `firebase_app_distribution_get_latest_release` command after the upload completes to grab the URL as well. I think the variable name in the hash is `testingUrl`.

**Comment by Yerdikul** [comment]
> I see the links printed out in console, but I'm trying to implement a post to slack with the link. Any chance to have them in a variable?

We use a little link hack. It helps us to receive a link to the release and send it to QA.

`  
firebase_app_distribution_get_latest_release

release_name = Actions.lane_context[:FIREBASE_APP_DISTRO_LATEST_RELEASE][:name]
release_url = get_firebase_release_url(release_name, app_id)
` 
` 
def get_firebase_release_url (release_name, app_id)
    release_base_url = "https://appdistribution.firebase.google.com/testerapps/"
    release_id_path = release_name.split(app).last

    return release_base_url + app + release_id_path
  end
`

**Comment by Yerdikul** [comment]
> @angelica-snowit We saw the same thing when messing with our own use case. Thought I would mention it looks like you can use the `firebase_app_distribution_get_latest_release` command after the upload completes to grab the URL as well. I think the variable name in the hash is `testingUrl`.

testingUrl - available only for android?

**Comment by byates-fleetian** [comment]
I was unable to get the testingUrl to work (on android). Instead I made a work around by capturing the output in a text file and then extracting the urls with awk. That method is hacky though and I would love to be able to have the urls returned in an object.

**Comment by AndrewSB** [comment]
@angelica-snowit that's exactly what i wanted too- as a variable to webhoook over to our internal messaging tool. if you figure it out, can you share the fastlane snippet? @Yerdikul's current workaround still has this https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/285#issuecomment-1325226746 issue

**Comment by tagboola** [comment]
FYI we added this functionality in the latest release 🙂 

https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v0.5.0
