### ISSUE TITLE
How i can install this plugin when install Fastlane by Brew?

### ISSUE THREAD

**Issue by paulocoutinhox** [fastlane/fastlane-plugin-firebase_app_distribution#303]
Hi,

How i can install this plugin when install Fastlane by Brew?

Thanks.

**Comment by lfkellogg** [comment]
@paulocoutinhox You should be able to follow the usual setup instructions [here](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane), but if that's not working for some reason please reply with the errors you're seeing.
