### ISSUE TITLE
Filed to upload distribution. HTTP Error: 413. Unknown Error

### ISSUE THREAD

**Issue by CRoig** [fastlane/fastlane-plugin-firebase_app_distribution#36]
So, I am trying to upload a binary to Firebase using Firebase_App_Distribution plugin on Fastlane.

It seems a HTTP 413 error occurs. According to standard error codes 413 stands for "Payload Too Large". So maybe there is any kind of size limitation on the binary.

Note I am trying to upload an ipa about 1.12GB (xcarchive 2.09GB). See error message below:
```
[15:05:04]: ---------------------------------------
[15:05:04]: --- Step: firebase_app_distribution ---
[15:05:04]: ---------------------------------------
[15:05:05]: ▸ i  getting app details...
[15:05:09]: ▸ i  uploading distribution...
[15:05:10]: ▸ Error: failed to upload distribution. HTTP Error: 413, Unknown Error
Shell command exited with exit status 1 instead of 0.
```
Any one can confirm the size limitation? or maybe point me to the right direction?

**Comment by TKBurner** [comment]
Thanks. The limit is approximately 900MB and that is likely why you are running into this issue. We are looking into the frequency of this so we can make considerations going forward.

**Comment by CRoig** [comment]
Thanks for your answer. I will try to offload some of the contents of the app. I will close the issue then.
