### ISSUE TITLE
Configurable GoogleService-info.plist name

### ISSUE THREAD

**Issue by Robotex** [fastlane/fastlane-plugin-firebase_app_distribution#37]
Regarding the PR #33, it would be nice if the filename could be configurable as in our company we have different names for each production stage

**Comment by alexsinger** [comment]
Good idea! Feel free to submit a PR and we can take a look.

**Comment by Robotex** [comment]
Just submitted a PR

**Comment by Robotex** [comment]
Closing this issue as the PR has been merged in 0.2.2
