### ISSUE TITLE
[0.1.4] No actions found in Plugin version on Windows

### ISSUE THREAD

**Issue by welersonMelo** [fastlane/fastlane-plugin-firebase_app_distribution#40]
Hi. I'm trying to use firebase_app_distribution on my Fastfile. 
I followed the tutorial of Firebase website: [firebase_app_distribution tutorial link](https://firebase.google.com/docs/app-distribution/android/distribute-fastlane).
When I run the simple command `fastlane`, when it is installing the plugin 'firebase_app_distribution', no Actions are found. 

I did exactly the same thing above on Mac OS and it works with no errors.

I also read the thread: [[0.1.4] No actions found in Plugin version.](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/15) and tried each of the suggestions and nothing worked on Windows (including use 0.1.2 version of the plugin).

**OS**: `Windows Server 2016`
**Versions:**
Fastlane: `2.143.0`
Ruby: `2.7.0`

**Follow part of the Log**

[11:23:01]: Error loading plugin 'fastlane-plugin-firebase_app_distribution': No such file or directory - which firebase

[11:23:01]: It seems like you wanted to load some plugins, however they couldn't be loaded
[11:23:01]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
+-------------------------------------------+---------+------------------+
|                              Used plugins                              |
+-------------------------------------------+---------+------------------+
| Plugin                                    | Version | Action           |
+-------------------------------------------+---------+------------------+
| fastlane-plugin-firebase_app_distribution | 0.1.4   | No actions found |
+-------------------------------------------+---------+------------------+

[!] No actions were found while loading one or more plugins
    Please use `bundle exec fastlane` with plugins
    More info - https://docs.fastlane.tools/plugins/using-plugins/#run-with-plugins

C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:162: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here

**Comment by alexsinger** [comment]
In you Gemfile, can you double-check that the path (bolded below) is set to the location of your `Pluginfile`?

`plugins_path = File.join(File.dirname(__FILE__), **'./fastlane'**, 'Pluginfile')`

**Comment by welersonMelo** [comment]
Yes, both are in the same folder.
The line is:
`plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
 eval_gemfile(plugins_path) if File.exist?(plugins_path)
`

**Comment by alexsinger** [comment]
Not sure if this is the issue, but the log says `No such file or directory - which firebase`. Wonder if this [default value for the Firebase CLI](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/master/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L12) is causing problems on Windows. 

Do you have the [Firebase CLI](https://firebase.google.com/docs/cli#setup_update_cli) set up on the machine? Can you try explicitly setting `firebase_cli_path` in your Fastfile config?

**Comment by welersonMelo** [comment]
Yes I have done that. I have set `firebase_cli_path` manually on Fastfile and I got the same error.
Because the error is before Fastfile be executed. 

And  seen the [code](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/master/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L12), I understood what is the "which" of the log. The `which` command does not exist on Windows, I thing that is the problem.

**Comment by alexsinger** [comment]
I don't have a Windows machine so can't test it out. Can you try commenting or editing the default `which` command to see if that fixes it?

**Comment by welersonMelo** [comment]
Hello!
Yes. It works on Windows when using `where` command.  Thank you.
What now to it to be fixed?

**Comment by alexsinger** [comment]
Oh great! I'm glad that solved it. Would you be up for submitting a PR to help fix it? Our team doesn't have a Windows machine so it's hard for us to test it out.

**Comment by ivevasiljevic** [comment]
Hello!

I have the same problem on Windows (same case) and reading these comments I don't understand where should I modify this `which `command to `where`?

Thanks!

**Comment by renatosousa-git** [comment]
> Hello!
> 
> I have the same problem on Windows (same case) and reading these comments I don't understand where should I modify this `which `command to `where`?
> 
> Thanks!

Algo parecido com esse caminho, o local onde você encontrara o arquivo para modificar...

C:\tools\ruby27\lib\ruby\gems\2.7.0\gems\fastlane-plugin-firebase_app_distribution-0.1.4\lib\fastlane\plugin\firebase_app_distribution\actions

**Comment by Rissmon** [comment]
Now i am having a error **firebase_cli_path: missing path to firebase cli tool. Please install firebase in $PATH or specify path**

**Comment by Rissmon** [comment]
> 
> 
> I was also facing the error **No actions found in Plugin version.**
> Thanks @welersonMelo @alexsinger Followed your comment and now I am having a different error **firebase_cli_path: missing path to firebase cli tool. Please install firebase in $PATH or specify path**

Again Thanks for the fix. firebase_cli_path issue is solved by adding the path explicity:
Fastfile
`
desc "Submit a new Beta Build"
  lane :distribute do
    build_android_app(task: "assembleQcRelease")
    firebase_app_distribution(
        app: "xxxxxxx",
        firebase_cli_path:"C:/Users/RISSMON/AppData/Roaming/npm/firebase"
    )`

**Comment by vicorious** [comment]
> Hello!
> 
> I have the same problem on Windows (same case) and reading these comments I don't understand where should I modify this `which `command to `where`?
> 
> Thanks!

Please, follow next steps for windows users.

First, in flutter project.

bundle install --path vendor/bundle

Second 

**flutter-project**\android\vendor\bundle\ruby\**2.x.x**\gems\fastlane-plugin-firebase_app_distribution-0.1.4\lib\fastlane\plugin\firebase_app_distribution\actions\**firebase_app_distribution_action.rb**

Change line.
`which firebase`

to

`where firebase`

And it works!!
