### ISSUE TITLE
Errors when building on Jenkins (with Service Account)

### ISSUE THREAD

**Issue by lordkiz** [fastlane/fastlane-plugin-firebase_app_distribution#42]
I get the error `Invalid default value for firebase_cli_path, doesn't match verify_block` when building on jenkins. I understand this is because I did not pass a `firebase_cli_path` as a param. 
However, I can see that from the docs you can use service-accounts and set an env variable `GOOGLE_APPLICATION_CREDENTIALS` as the path to the service account's file, all of which I have done.
Any idea how/if this plugin uses service-accounts?

fastlane-plugin-firebase_app_distribution: 0.1.4

**Comment by alexsinger** [comment]
The fastlane plugin makes all calls through the Firebase CLI, so authentication and uploads are all handed through it. When you set `GOOGLE_APPLICATION_CREDENTIALS`, those credentials are used to authenticate the Firebase CLI calls. You still need to set the `firebase_cli_path` to tell plugin where your Firebase CLI is installed.

**Comment by lordkiz** [comment]
Thanks @alexsinger
