### ISSUE TITLE
Support for AAB

### ISSUE THREAD

**Issue by danielgomezrico** [fastlane/fastlane-plugin-firebase_app_distribution#44]
Hi

Thanks for this awesome plugin, it worked really easy the first time I tried.

Currently the plugin just support this property `apk_path`.

It will be cool if you can add support for AAB ([app bundles](https://developer.android.com/guide/app-bundle)), so the testers can test the real apk based on it's device, see installed app size and those kind of things that will vary if you use AAB instead of APK.

**Comment by kevinkokomani** [comment]
Hello, first off thank you for this great feedback!

We're currently evaluating best practices for unblocking your use case. The path forward will likely still be using APKs but we'd love to be able to support developers like you that are building AABs. I don't have specifics yet but I just wanted to let you know that we're definitely looking at this :)

**Comment by jcchikikomori** [comment]
Hi. This may be mandatory on 2021 since Google doesn't recommend uploading APK to Play Store anymore

https://android-developers.googleblog.com/2020/08/recent-android-app-bundle-improvements.html

**Comment by DavidBertet** [comment]
Our solution doesn't fully address the issue as we are using a universal apk from the bundle, but it allows us to push the same exact production app to Firebase for future update testing

It's basic stuff, but I put that here just in case it helps someone with a similar need

```
lane :build_playstore do
    # Build the project, that is going to create an .aab file
    gradle(...)

    # Whe need to convert the .aab to a conventional .apk in order to send it to Fibase
    
    # Remove old stuff is still present
    sh("rm -rf ./tmp")
    
    # Create temporary folder where we are going to put the .apk in
    sh("mkdir -p ./tmp")
    
    # Convert the .aab to a universal .apks (that contains the .apk)
    sh("java", "-jar", "../../tools/bundletool/bundletool.jar",
       "build-apks",
       "--bundle", lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],
       "--output", "./tmp/app.apks",
       "--mode", "universal",
       "--ks", ENV['KEYSTORE'],
       "--ks-pass", "pass:#{ENV['RLS_STOREP']}",
       "--ks-key-alias", "playstore",
       "--key-pass", "pass:#{ENV['RLS_KEYP']}",
       log: false)
    
    # Unzip the apks file created
    sh("cd ./tmp && unzip app.apks")
    
    # Upload the universal apk to firebase
    firebase_app_distribution(
      app: ENV['FIREBASE_APPID'],
      apk_path: './fastlane/tmp/universal.apk',
      groups: ENV['FIREBASE_GROUP_LIST'],
      release_notes: ENV['FIREBASE_RELEASE_NOTES']
    )
    
    # Clean temporary files
    sh("rm -rf ./tmp")

    upload_to_play_store(...)
end
```

`bundletool.jar` is the tool Google offers to play with AppBundles https://github.com/google/bundletool/releases

**Comment by danielgomezrico** [comment]
AAB is currently supported now from the firebase console, is there any update on this from this side?

![image](https://user-images.githubusercontent.com/76348/118280612-01010100-b492-11eb-8a40-efdad79d6070.png)

**Comment by tagboola** [comment]
Yes! @danielgomezrico you can now upload AAB's with the fastlane plugin. See the link to the documentation below.
https://firebase.google.com/docs/app-distribution/android/distribute-fastlane?apptype=aab

**Comment by danielgomezrico** [comment]
O M G, awesome! thanks for that
