### ISSUE TITLE
DSYM upload handling?

### ISSUE THREAD

**Issue by rockshassa** [fastlane/fastlane-plugin-firebase_app_distribution#47]
Does an invocation of `firebase_app_distribution` upload DSYMs as well?
I can't find a clear answer in the docs.

**Comment by cvaghela** [comment]
No, invocation of `firebase_app_distribution` does not upload DSYMs.

**Comment by Busta117** [comment]
use `upload_symbols_to_crashlytics` to upload the SDYMs after upload the binary

**Comment by Dougherty** [comment]
I had this problem but thanks to [targetpayandbenefits](https://www.targetehr.us/targetpayandbenefits/)
