### ISSUE TITLE
Error: failed to upload distribution. HTTP Error: 403, Unknown Error

### ISSUE THREAD

**Issue by ToyboxZach** [fastlane/fastlane-plugin-firebase_app_distribution#78]
Fairly recently I've started to get this error 
Error: failed to upload distribution. HTTP Error: 403, Unknown Error
anytime I do this task for android
```
lane :beta do |values|
    
    gradle(task: "assemble",build_type: "Release")
    
    firebase_app_distribution(
      app:'<myAPI>',
        groups:'Team',
        release_notes: changelog_from_git_commits(commits_count: 10, pretty: '%h %s', merge_commit_filtering: 'exclude_merges')
      )
  end
```

It takes about 20 minutes at the 
i  uploading distribution...

```

[15:50:27]: ---------------------------------------
[15:50:27]: --- Step: firebase_app_distribution ---
[15:50:27]: ---------------------------------------
[15:50:29]: ▸ i  getting app details...
[15:50:31]: ▸ i  uploading distribution...

[16:12:24]: ▸ Error: failed to upload distribution. HTTP Error: 403, Unknown Error
```

I have also noticed my equivalent iOS beta taking a really long time at the upload step. 

Was there a recent updating step I missed? This was working fine about a month ago

**Comment by cvaghela** [comment]
Can you try using the following instead:

```
platform :android do
      desc "My awesome app"
      lane :distribute do
          build_android_app(...) # build_android_app is a built-in fastlane action.

          firebase_app_distribution(
              app: "1:123456789:android:abcd1234",
              groups:'Team',
        release_notes: changelog_from_git_commits(commits_count: 10, pretty: '%h %s', merge_commit_filtering: 'exclude_merges'),
              firebase_cli_path: "/absolute/path/to/firebase/cli/binary"
          )

      end
  end
```

**Comment by ToyboxZach** [comment]
The same problem is happening

**Comment by ToyboxZach** [comment]
I have now tried distribution directly with the firebase tool, and I still get the timeout, where would be the right place to log a bug/get support for the command line tool?

**Comment by ToyboxZach** [comment]
So update from my end, I ended up checking and my upload speed was like 0.3 Mb/s. So that was the major cause. This was still much slower than uploading through a browser, but it was only excessively slow because of that. I got my internet fixed and now I don't end up with a timeout. So this issue as is can be closed, but there are still some issues with upload speed with the CLI.
