### ISSUE TITLE
[BUG] It took longer than expected to process your APK, please try again

### ISSUE THREAD

**Issue by stevepopovich** [fastlane/fastlane-plugin-firebase_app_distribution#82]
I am not sure why my APK won't upload. This is something that has started happening more and more in our build pipeline. It doesn't happen everytime, but happens enough that it needs to be addressed. Here is the command being run:

```
> Task :app:appDistributionUploadQa
Found APK at ./app/build/outputs/apk/qa/app-universal-qa.apk.
Uploading APK to Firebase App Distribution...
Getting appId from output of google services plugin
This APK has not been uploaded before.
Uploading the APK.
Uploaded APK successfully 202
> Task :app:appDistributionUploadQa FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:appDistributionUploadQa'.
> App Distribution failed to fetch release information: It took longer than expected to process your APK, please try again
```

I suspect our APK is getting quite large and could be related. Any way I can increase the timeout or something? Any other ideas?

**Comment by cvaghela** [comment]
What is the size of the APK and the version of Firebase CLI that are you using?

**Comment by stevepopovich** [comment]
This was resolved by upgrading our version of firebase distribution version, as per firebase support
