### ISSUE TITLE
Authentication isn't working with Google Service Account.

### ISSUE THREAD

**Issue by birogellert** [fastlane/fastlane-plugin-firebase_app_distribution#84]
I am using Fastlane in a CI environment to upload my Android APK to Firebase.

I have a valid service account for the authentication and the `GOOGLE_APPLICATIONS_CREDENTIALS` environment variable is showing the path of the key to this service account. 

Last time when the upload was triggered, it was working fine (Dec 19, 2019), now I get this error:

```Error: failed to fetch app information. HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.```

I am seeing issues like #65, #66, #67, are these related to my issue? Did something change in the Firebase Auth flow in the meantime? I am a little bit confused since this was working before.

**Comment by cvaghela** [comment]
Can you try logging out `firebase logout` then log-in `firebase login` again or just refresh the token with `firebase login --reauth`

**Comment by birogellert** [comment]
> Can you try logging out `firebase logout` then log-in `firebase login` again or just refresh the token with `firebase login --reauth`

That won't help, unfortunately. I wasn't using `firebase login` before, my CI job is running in a separated docker environment and I am using a Google Service Account key for the authentication.

**Comment by birogellert** [comment]
Of course, I could get a token from the `firebase login:ci` and set the FIREBASE_TOKEN environment variable, but I was preferring the other way with the service account and the `GOOGLE_APPLICATIONS_CREDENTIALS`.

**Comment by birogellert** [comment]
Okay, turned out that by mistake there was a `FIREBASE_TOKEN` variable left in the CI setup and eventually that became invalid. Removing it fixed the problem.
